//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom12_Website_Ban_Cua.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiVanChuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiVanChuyen()
        {
            this.DatHangs = new HashSet<DatHang>();
        }
    
        public int MaNguoiVanChuyen { get; set; }
        public string TenNguoiVanChuyen { get; set; }
        public string SDTNguoiVanChuyen { get; set; }
        public string EmailNguoiVanChuyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHang> DatHangs { get; set; }
    }
}
