//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom12_Website_Ban_Cua.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int MaPhanQuyen { get; set; }
        public string MaLoaiNguoiDung { get; set; }
        public string MaQuyenQuanTri { get; set; }
    
        public virtual LoaiNguoiDung LoaiNguoiDung { get; set; }
        public virtual QuyenQuanTri QuyenQuanTri { get; set; }
    }
}
