//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom12_Website_Ban_Cua.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauHoTro
    {
        public int MaYeuCau { get; set; }
        public int MaNguoiDung { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> MaTrangThai { get; set; }
        public System.DateTime NgayYeuCau { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TrangThai TrangThai { get; set; }
    }
}
